language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
before_script:
  - npm install
script:
  - npm run build

after_success:
  if [ -n "$github_token" ]; then
  cd "$TRAVIS_BUILD_DIR"
  # This generates a `web` directory containing the website.
  make web
  cd web
  git init
  git checkout -b gh-pages
  git add .
  git -c user.name='travis' -c user.email='travis' commit -m init
  # Make sure to make the output quiet, or else the API token will leak!
  # This works because the API key can replace your password.
  git push -f -q https://<me>:$github_token@github.com/<me>/<myrepo>-gh-pages gh-pages &>/dev/null
  cd "$TRAVIS_BUILD_DIR"
  fi

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token : $github_token
#  keep_history: true
#  on:
#    branch: gh-pages
